spring:
  data:
    mongodb:
      database: ecommerce
      uri: ${MONGODB_ATLAS_URI}


together-ai:
  api-key: ${TOGETHER_AI_API_KEY}
  base-url: ${TOGETHER_AI_BASE_URL}
  embedding-model: ${TOGETHER_AI_EMBEDDING_MODEL}
